In [2]:
#Importing Libraries

import pandas as pd
import numpy 
import json
import csv
import requests
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# Reading the file

df = pd.read_csv('animes.csv', encoding="unicode_escape", error_bad_lines=False)

In [4]:
df

anime_id                                              title  \
0            1                           Zombieland Saga: Revenge   
1            2                                Yuukoku no Moriarty   
2            3                                Yesterday wo Utatte   
3            4                             Yes ka No ka Hanbun ka   
4            5  Yahari Ore no Seishun Love Comedy wa Machigatt...   
5            6                                    Wu Shan Wu Xing   
6            7                                    World Trigger 2   
7            8                            Violet Evergarden Movie   
8            9                                Umibe no E‰tranger   
9           10                          Toaru Kagaku no Railgun T   
10          11  Slime Taoshite 300-nen, Shiranai Uchi ni Level...   
11          12                    Shokugeki no Souma: Gou no Sara   
12          13                  Shironeko Project: Zero Chronicle   
13          14                                    Shirobako Movie   
14          15                Shingeki no Kyojin The Final Season   
15          16                        Seitokai Yakuindomo Movie 2   
16          17   Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season   
17          18                          Princess Connect! Re:Dive   
18          19                      Peter Grill to Kenja no Jikan   
19          20                                                Pet   
20          21                Oshi ga Budoukan Ittekuretara Shinu   
21          22                        Omoi, Omoware, Furi, Furare   
22          23                             Non Non Biyori Nonstop   
23          24                            No Guns Life 2nd Season   
24          25  Maou Gakuin no Futekigousha: Shijou Saikyou no...   
25          26                      Majutsushi Orphen Hagure Tabi   
26          27                                   Majo no Tabitabi   
27          28                                          Listeners   
28          29                                    Lapis Re:LiGHTs   
29          30                                       Kyokou Suiri   
...        ...                                                ...   
2836      2837                                         Gingitsune   
2837      2838                     Kiniro no Corda: Secondo Passo   
2838      2839                                    Date A Live III   
2839      2840            Chuunibyou demo Koi ga Shitai! Ren Lite   
2840      2841                                      Aquarion Evol   
2841      2842                                           Aoi Hana   
2842      2843                              Ai Yori Aoshi: Enishi   
2843      2844  Koukyoushihen Eureka Seven: Pocket ga Niji de ...   
2844      2845                                   Mouretsu Pirates   
2845      2846                     Fate/kaleid liner Prisma Illya   
2846      2847                                           Tamayura   
2847      2848                                     Kaze no Stigma   
2848      2849               Uta no †Prince-sama Maji Love 1000%   
2849      2850  Dragon Ball Z Movie 09: Ginga Girigiri!! Bucch...   
2850      2851                                          Cencoroll   
2851      2852                            Spiral: Suiri no Kizuna   
2852      2853                                     Plastic Neesan   
2853      2854                                          Air Movie   
2854      2855                                       Heavy Object   
2855      2856                                 Deadman Wonderland   
2856      2857                          Gundam Build Fighters Try   
2857      2858                                     Robotics;Notes   
2858      2859  Pokemon Movie 02: Maboroshi no Pokemon Lugia B...   
2859      2860                                         Amagami SS   
2860      2861                          Net-juu no Susume Special   
2861      2862                                        Naruto x UT   
2862

In [5]:
features = ["title", "genre", "aired", "episodes"]

In [6]:
df.shape[0]

2866

In [7]:
#Combining features that are factors for choosing an anime
def combine_features(data):
    
    features = []
    
    for i in range(0, data.shape[0]):
        features.append(data["title"][i]+' '+data['genre'][i]+' '+str(data['aired'][i])+' '+str(data['episodes'][i]))
                        
    return features

#data["title"][i]+' '+data['genre'][i]+' '+str(data['aired'][i])+' '+str(data['episodes'][i])

In [8]:
#Create a column for all the combined features
df['features'] = combine_features(df)
#Show data
df["features"][0]

"Zombieland Saga: Revenge ['Music', 'Comedy', 'Supernatural'] 2020 12"

In [9]:
df

anime_id                                              title  \
0            1                           Zombieland Saga: Revenge   
1            2                                Yuukoku no Moriarty   
2            3                                Yesterday wo Utatte   
3            4                             Yes ka No ka Hanbun ka   
4            5  Yahari Ore no Seishun Love Comedy wa Machigatt...   
5            6                                    Wu Shan Wu Xing   
6            7                                    World Trigger 2   
7            8                            Violet Evergarden Movie   
8            9                                Umibe no E‰tranger   
9           10                          Toaru Kagaku no Railgun T   
10          11  Slime Taoshite 300-nen, Shiranai Uchi ni Level...   
11          12                    Shokugeki no Souma: Gou no Sara   
12          13                  Shironeko Project: Zero Chronicle   
13          14                                    Shirobako Movie   
14          15                Shingeki no Kyojin The Final Season   
15          16                        Seitokai Yakuindomo Movie 2   
16          17   Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season   
17          18                          Princess Connect! Re:Dive   
18          19                      Peter Grill to Kenja no Jikan   
19          20                                                Pet   
20          21                Oshi ga Budoukan Ittekuretara Shinu   
21          22                        Omoi, Omoware, Furi, Furare   
22          23                             Non Non Biyori Nonstop   
23          24                            No Guns Life 2nd Season   
24          25  Maou Gakuin no Futekigousha: Shijou Saikyou no...   
25          26                      Majutsushi Orphen Hagure Tabi   
26          27                                   Majo no Tabitabi   
27          28                                          Listeners   
28          29                                    Lapis Re:LiGHTs   
29          30                                       Kyokou Suiri   
...        ...                                                ...   
2836      2837                                         Gingitsune   
2837      2838                     Kiniro no Corda: Secondo Passo   
2838      2839                                    Date A Live III   
2839      2840            Chuunibyou demo Koi ga Shitai! Ren Lite   
2840      2841                                      Aquarion Evol   
2841      2842                                           Aoi Hana   
2842      2843                              Ai Yori Aoshi: Enishi   
2843      2844  Koukyoushihen Eureka Seven: Pocket ga Niji de ...   
2844      2845                                   Mouretsu Pirates   
2845      2846                     Fate/kaleid liner Prisma Illya   
2846      2847                                           Tamayura   
2847      2848                                     Kaze no Stigma   
2848      2849               Uta no †Prince-sama Maji Love 1000%   
2849      2850  Dragon Ball Z Movie 09: Ginga Girigiri!! Bucch...   
2850      2851                                          Cencoroll   
2851      2852                            Spiral: Suiri no Kizuna   
2852      2853                                     Plastic Neesan   
2853      2854                                          Air Movie   
2854      2855                                       Heavy Object   
2855      2856                                 Deadman Wonderland   
2856      2857                          Gundam Build Fighters Try   
2857      2858                                     Robotics;Notes   
2858      2859  Pokemon Movie 02: Maboroshi no Pokemon Lugia B...   
2859      2860                                         Amagami SS   
2860      2861                          Net-juu no Susume Special   
2861      2862                                        Naruto x UT   
2862

In [10]:
#Convert the text from the new column to a matrix of word counts:
cm = CountVectorizer(stop_words='english').fit_transform(df['features'])

In [11]:
#Get Cosine Similarity Matrix from Count Matrix

cs = cosine_similarity(cm, cm)

#print scores

print(cs)

/Users/saisanthoshthunga/anaconda3/lib/python3.7/site-packages/sklearn/metrics/pairwise.py:56: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.float


[[1.         0.25       0.2236068  ... 0.23570226 0.         0.09128709]
 [0.25       1.         0.2236068  ... 0.23570226 0.         0.        ]
 [0.2236068  0.2236068  1.         ... 0.31622777 0.         0.32659863]
 ...
 [0.23570226 0.23570226 0.31622777 ... 1.         0.         0.25819889]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.09128709 0.         0.32659863 ... 0.25819889 0.         1.        ]]


In [12]:
#Get the title of the anime the viewer likes
Title = df["title"][909]
Title

'Kimetsu no Yaiba'

In [13]:
#Get the anime_id
anime_id = df[df.title == Title]["anime_id"].values[0]
#Show anime_id
anime_id

910

In [14]:
#Create a list of tuples in the form (anime_id, similarity score)
scores = list(enumerate(cs[anime_id]))
print(scores[0:6])

[(0, 0.24999999999999994), (1, 0.12499999999999997), (2, 0.0), (3, 0.0), (4, 0.16666666666666666), (5, 0.0)]


In [15]:
sorted_scores = sorted(scores, key=lambda x:x[1], reverse=True)
sorted_scores = sorted_scores[1:]
sorted_scores[:10]

[(544, 0.6681531047810608),
 (592, 0.6681531047810608),
 (100, 0.533001790889026),
 (638, 0.533001790889026),
 (2684, 0.533001790889026),
 (1229, 0.4999999999999999),
 (217, 0.47434164902525683),
 (2414, 0.47434164902525683),
 (906, 0.4714045207910316),
 (800, 0.4472135954999579)]

In [16]:
#print the top 10 recommended animes

j = 0

print('Top 10 Recommended Animes ' + Title + ' are:\n:')
for item in sorted_scores:
    anime_title = df[df.anime_id == item[0]]['title'].values[0]
    print(j+1, anime_title)
    j = j+1
    
    if j >= 10:
        break

Top 10 Recommended Animes Kimetsu no Yaiba are:
:
1 Bakuman. 2nd Season
2 Rainbow: Nisha Rokubou no Shichinin
3 Magic Kaito
4 Mushishi Zoku Shou 2nd Season
5 Strawberry Panic
6 Monochrome Factor
7 Kamisama Hajimemashita OVA
8 Beatless
9 Fullmetal Alchemist: Brotherhood
10 Aoi Bungaku Series
